remove v prefix

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -78,6 +78,7 @@ jobs:
           pwd
           ls -la
           export VER=$(cat VERSION)
+          export VER=${VER#"v"}
           export PIPERR=$(pip install tapdance==versioncheck 2>&1)
           echo "Checking for PyPi availability of version $VER"
           if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not yet found..."; sleep 30; } fi;
@@ -92,7 +93,7 @@ jobs:
           export PIPERR=$(pip install tapdance==versioncheck 2>&1)
           if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not yet found..."; sleep 30; } fi;
           export PIPERR=$(pip install tapdance==versioncheck 2>&1)
-          if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not found. Giving up. Last message from PyPi was $PIPERR"; } fi;
+          if [[ $PIPERR == *"$VER"* ]]; then { echo "Yes"; } else { echo "Not found. Giving up. Last message from PyPi was $PIPERR"; exit 1; } fi;
 
       # - name: Sleep before install
       #   run: |
